package com.example.sympmeds;

import java.util.ArrayList;

import jxl.Cell;
import jxl.Sheet;
import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.Menu;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.Spinner;
import android.widget.TextView;

/*
 * This shows all the information on the symptom that was chosen from the previous activity which includes:
 * 			the symptom name
 * 			a description of the symptom
 * 			the list of drugs that treat the symptom
 * The list of drugs is in a spinner like the previous activity.  There is also a button opens the next
 * activity with the drug chosen from the spinner.
 */
public class DrugList extends Activity {
	public final static String DRUG_INFO = "com.example.sympmeds.INFO";
	private final static int SYMPTOM_SHEET = 0;
	private final static int STARTING_ROW = 1;
	private final static int SYMPTOM_NAME_COL = 0;
	private final static int SYMPTOM_DESC_COL = 1;
	private final static int STARTING_COL = 2;
	
	/**onCreate() is called when the DrugList activity is started, which is when the
	 * Search button from the SymptomList activity is pushed.
	 */
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);

		// Get the symptom from the intent; this area is not done
		Intent intent = getIntent();
		String symptom = intent.getStringExtra(SymptomList.DRUG_LIST);

		setContentView(R.layout.activity_drug_list);

		//get symptom sheet from the database variable
		Sheet sheet = MainActivity.database.getSheet(SYMPTOM_SHEET);

		//finds the correct symptom
		int symptomNumber;
		Cell cell;
		String text = "";
		for(symptomNumber = STARTING_ROW; symptomNumber < sheet.getRows(); symptomNumber++) {
			cell = sheet.getCell(SYMPTOM_NAME_COL, symptomNumber);
			text = cell.getContents();
			//if it is the correct symptom, leave the for-loop
			if (symptom.equals(text)) {
				break;
			}
		}

		//enters strings into textViews
		//symptom name
        TextView sympName = (TextView) findViewById(R.id.sympName_textView);
        sympName.setText(text);
        //symptom description
        cell = sheet.getCell(SYMPTOM_DESC_COL, symptomNumber);
        text = cell.getContents();
        TextView sympDesc = (TextView) findViewById(R.id.sympDesc_textView);
        sympDesc.setText(text);

        //put the list of drugs that treat the symptom into an array
		ArrayList<String> arrayList = new ArrayList<String>();
		for(int drugNumber = STARTING_COL; drugNumber < sheet.getColumns(); drugNumber++) {
			cell = sheet.getCell(drugNumber, symptomNumber);
			text = cell.getContents();
			//if the list of drugs ends prematurely(list is smaller than a list from another symptom), leave the for-loop
			if (text.equals("/////")) {
				break;
			}
			arrayList.add(text);
		}
		
		//enter array into spinner
		String[] array = arrayList.toArray(new String[arrayList.size()]);
		Spinner spinner = (Spinner) findViewById(R.id.drug_spinner);
		ArrayAdapter<CharSequence> adapter = new ArrayAdapter<CharSequence>(this, android.R.layout.simple_spinner_item, array);
		adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
		spinner.setAdapter(adapter);
	}

    /**
     * This was generated by default by Eclipse
     */
	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.drug_list, menu);
		return true;
	}

    /** Called when the user clicks the Get Info button.
     * It calls up the DrugInfo activity with all the information that is respect to
     * what is selected from the spinner in this activity.
     */
    public void getInfo (View view) {
    	// Do something in response to button
		Intent intent = new Intent(this, DrugInfo.class);
		Spinner spinner = (Spinner) findViewById(R.id.drug_spinner);
		String text = spinner.getSelectedItem().toString();
		intent.putExtra(DRUG_INFO, text);
		startActivity(intent);
    }
}
