package com.example.sympmeds;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;

import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import android.app.Activity;
import android.content.Intent;
import android.content.res.AssetManager;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.Spinner;
import android.widget.TextView;

public class DrugList extends Activity {
	public final static String DRUG_INFO = "com.example.sympmeds.INFO";

	/**onCreate() is called when the DrugList activity is started, which is when the
	 * Search button from the SymptomList activity is pushed.
	 */
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);

		// Get the symptom from the intent; this area is not done
		Intent intent = getIntent();
		String symptom = intent.getStringExtra(SymptomList.DRUG_LIST);

		setContentView(R.layout.activity_drug_list);

		AssetManager assetManager = getResources().getAssets();
		InputStream inputStream = null;
		try{
			inputStream = assetManager.open("Database.xls");
		} catch(IOException e) {
			Log.e("SYMPMEDS", "error 1");
			e.printStackTrace();
		}
		Log.i("SYMPMEDS", inputStream.toString());
		Workbook wb = null;
		try{
			try {
				wb = Workbook.getWorkbook(inputStream);
				Log.i("SYMPMEDS", "wb = workbook worked");

			} catch (IOException e) {
				Log.e("SYMPMEDS", "error 2");
				e.printStackTrace();
			}
		} catch(BiffException e) {
			Log.e("SYMPMEDS", "error 3");
			e.printStackTrace();
		}
		try {
			inputStream.close();
			Log.i("SYMPMEDS", "inputStream.close() worked");
		} catch (IOException e) {
			Log.e("SYMPMEDS", "error 4");
			e.printStackTrace();
		}
		Sheet sheet = wb.getSheet(0);
		Log.i("SYMPMEDS", sheet.getName());
		//List<String> list = new ArrayList<String>();
		//String rowNum = sheet.getRows() + "";
		//Log.i("SYMPMEDS", rowNum);

		//finds the correct symptom
		int i;
		Cell cell;
		String text = "";
		for(i = 1; i < sheet.getRows(); i++) {
			cell = sheet.getCell(0, i);
			text = cell.getContents();
			if (symptom.equals(text)) {
				break;
			}
		}
		Log.i("SYMPMEDS", "i = " + i);

		//enters strings into textViews
        TextView sympName = (TextView) findViewById(R.id.sympName_textView);
        sympName.setText(text);
        cell = sheet.getCell(1, i);
        text = cell.getContents();
        TextView sympDesc = (TextView) findViewById(R.id.sympDesc_textView);
        sympDesc.setText(text);
        Log.i("SYMPMEDS", "textViews worked");

        //enter array into spinner
		ArrayList<String> arrayList = new ArrayList<String>();
		for(int j = 2; j < sheet.getColumns(); j++) {
			cell = sheet.getCell(j, i);
			text = cell.getContents();
			if (text.equals(R.string.end)) {
				break;
			}
			arrayList.add(text);
			//Log.i("SYMPMEDS", text + "\t" + i);
		}
		Log.i("SYMPMEDS", "array is set");
		String[] array = arrayList.toArray(new String[arrayList.size()]);
		Spinner spinner = (Spinner) findViewById(R.id.drug_spinner);
		ArrayAdapter<CharSequence> adapter = new ArrayAdapter<CharSequence>(this, android.R.layout.simple_spinner_item, array);
		adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
		spinner.setAdapter(adapter);
		Log.i("SYMPMEDS", "spinner works");
	}

    /**
     * This was generated by default by Eclipse
     */
	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.drug_list, menu);
		return true;
	}

    /** Called when the user clicks the Get Info button.
     * It calls up the DrugInfo activity with all the information that is respect to
     * what is selected from the spinner in this activity.
     */
    public void getInfo (View view) {
    	// Do something in response to button}
		Intent intent = new Intent(this, DrugInfo.class);
		Spinner spinner = (Spinner) findViewById(R.id.drug_spinner);
		String text = spinner.getSelectedItem().toString();
		intent.putExtra(DRUG_INFO, text);
		startActivity(intent);
    }
}
