package com.example.sympmeds;

import android.os.Bundle;
import android.app.Activity;
import android.content.Intent;
import android.view.Menu;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.Spinner;
import android.widget.TextView;

public class DrugList extends Activity {
	public final static String DRUG_INFO = "com.example.sympmeds.INFO";

	/**onCreate() is called when the MainActivity activity is started,
	 * which is at the start of the application.
	 * It has the default code plus code to start up the spinner.
	 */
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		
		// Get the symptom from the intent; this area is not done
		Intent intent = getIntent();
		String symptom = intent.getStringExtra(MainActivity.DRUG_LIST);
		
		setContentView(R.layout.activity_drug_list);
		
		String[] drugList = getResources().getStringArray(R.array.symptom_list);
        Spinner spinner = (Spinner) findViewById(R.id.spinner2);
        ArrayAdapter<CharSequence> adapter;
        TextView myTextName = (TextView) findViewById(R.id.textView2);
        TextView myTextDescription = (TextView) findViewById(R.id.textView3);
        myTextName.setText(symptom);
        String[] descList = getResources().getStringArray(R.array.symptom_description);
        if(symptom.equals(drugList[0])) {
        	adapter= ArrayAdapter.createFromResource(
        			this, R.array.fever_list, android.R.layout.simple_spinner_item);
        	myTextDescription.setText(descList[0]);
        } else if(symptom.equals(drugList[1])) {
        	adapter= ArrayAdapter.createFromResource(
        			this, R.array.headache_list, android.R.layout.simple_spinner_item);
        	myTextDescription.setText(descList[1]);
        } else if(symptom.equals(drugList[2])) {
        	adapter= ArrayAdapter.createFromResource(
        			this, R.array.coughing_list, android.R.layout.simple_spinner_item);
        	myTextDescription.setText(descList[2]);
        } else if(symptom.equals(drugList[3])) {
        	adapter= ArrayAdapter.createFromResource(
        			this, R.array.cold_list, android.R.layout.simple_spinner_item);
        	myTextDescription.setText(descList[3]);
        } else if(symptom.equals(drugList[4])) {
        	adapter= ArrayAdapter.createFromResource(
        			this, R.array.flu_list, android.R.layout.simple_spinner_item);
        	myTextDescription.setText(descList[4]);
        } else {
        	adapter= ArrayAdapter.createFromResource(
        			this, R.array.drug_list, android.R.layout.simple_spinner_item);
        	myTextDescription.setText(R.string.unknown);
        }
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spinner.setAdapter(adapter);
	}

    /**
     * This was generated by default by Eclipse
     */
	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.drug_list, menu);
		return true;
	}
	
    /** Called when the user clicks the Get Info button.
     * This calls up the DrugInfo activity with information with respect to 
     * the drug displayed from this spinner.
     */
    public void getInfo (View view) {
    	// Do something in response to button}
		Intent intent = new Intent(this, DrugInfo.class);
		Spinner spinner = (Spinner) findViewById(R.id.spinner2);
		String text = spinner.getSelectedItem().toString();
		try {
			intent.putExtra(DRUG_INFO, text);
		} catch (Exception e) {
		     // This will catch any exception, because they are all descended from Exception
		}
		startActivity(intent);
    }

}
